config/routes.rb
Rails.application.routes.draw do
  

  root 'top_pages#home'

  devise_scope :user do
    get     '/signup',         to: 'users/registrations#new'
    post    '/signup',         to: 'users/registrations#create'
    get     '/users/edit',     to: 'users/registrations#edit'
    patch   '/users/:id',      to: 'users/registrations#update'
    delete  '/users/:id',      to: 'users/registrations#delete'
    get     'login',           to: 'users/sessions#new'
    post    '/login',          to: 'users/sessions#create'
    delete  '/logout',         to: 'users/sessions#destroy'
    get     '/password/reset/new', to: 'users/passwords#new'
    post    'user/password',       to: 'users/passwords#create'
    get     'users/password/edit', to: 'users/passwords#edit'
    patch   'users/password', to: 'users/passwords#update'
    
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords', 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  } 
  
  resources :users do
    member do
      get :following, :followers
      get :like
    end
  end
  
  resources :users,         only: [:index, :show, :create, :edit, :destroy]
  resources :microposts,    only: [:create, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes,         only: [:create, :destroy]
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :content, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @micropost = Micropost.find(params[:micropost_id])
    @comment = Comment.new
  end

  def create
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = 'コメントしました'
      redirect_to request.referrer || root_url
    else
      flash[:success] = 'コメントできませんでした'
      render 'new'
  end
  end

  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referrer || root_url
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comments_area.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table id="js-table-comment" class="table">
      <%= render comments %>
    </table>
  </div>
</div>

app/views/comments/create.js.erb
$('#js-table-comment').prepend("<%= j(render 'comment',{ comment: @comment }) %>");
$('#comment_body').val('')

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();

app/views/comments/new.html.erb
<% provide(:title, 'コメント') %>
<div class = "comment-wrapper border-top mb-10">
<% if @comment.blank? %>
<h3>コメントはまだありません</h3>
<% else %>
 <div class = "comments" >
<% @micropost.comments.each do |comment| %>
<%= link_to gravatar_for(comment.user, size: 50), comment.user %>
<div class = "user"><%= link_to comment.user.nickname, comment.user %></div>
 <div class = "text">
 <%= comment.content %>
</div>
<span class = "timestamp">
<%= time_ago_in_words(comment.created_at) %>前
</span>
 <% if @micropost.commented_by?(current_user) %>
  <%= link_to "消す", micropost_comment_path(micropost_id: @micropost,id: comment.id), method: :delete, data:{ confirm: "You sure?" } %>
  
 <% end %>
</div>
 <% end %>
 </div>
<% end %>
 <%= form_with(model: [@micropost, @comment], remote: true) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
 <div class="field">
 <%= f.text_area :content, placeholder: "コメントを入力して下さい",class: "form-control", rows: 5 %>
 </div>
 <%= f.submit "コメントする", class: "btn btn-primary" %>
 <% end %>
 </div>