config/routes.rb
Rails.application.routes.draw do
  

  root 'top_pages#home'

  devise_scope :user do
    get     '/signup',         to: 'users/registrations#new'
    post    '/signup',         to: 'users/registrations#create'
    get     '/users/edit',     to: 'users/registrations#edit'
    patch   '/users/:id',      to: 'users/registrations#update'
    delete  '/users/:id',      to: 'users/registrations#delete'
    get     'login',           to: 'users/sessions#new'
    post    '/login',          to: 'users/sessions#create'
    delete  '/logout',         to: 'users/sessions#destroy'
    get     '/password/reset/new', to: 'users/passwords#new'
    post    'user/password',       to: 'users/passwords#create'
    get     'users/password/edit', to: 'users/passwords#edit'
    patch   'users/password', to: 'users/passwords#update'
    
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords', 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  } 
  
  resources :users do
    member do
      get :following, :followers
      get :like
    end
  end
  
  resources :users,         only: [:index, :show, :create, :edit, :destroy]
  resources :microposts,    only: [:create, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes,         only: [:create, :destroy]
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 
  <div id="error_explanation">
    <div class= "alert alert-danger">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: object.errors.count,
                 resource: object.class.model_name.human.downcase)
       %>
         
    </h2>
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<%= render 'shared/search' %>
<% if @feed_items.any? %>
 <% render "shared/search" %>
  <ol class="feed">
    <%= render @feed_items %>
  </ol>
   <%= render "likes/like", micropost: @micropost %>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_user_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>


<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>

  <%= render "shared/error_messages" ,object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
  <span class ="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_search.html.erb
<%= form_with(scope: :search, url: users_path, method: :get, local: true) do |f| %>
  <%= f.label(:content, '投稿検索') %>
  <div class="field">
   <%= text_field_tag :content, params[:content] %>
  <%= f.submit('検索') %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/shared/_user_search.html.erb
<div class= "search">
  <%= form_with(scope: :search, url: users_path, method: :get, local: true) do |f| %>
  <%= f.label(:nickname, 'ユーザー検索') %>
    <div class="field">
      <%= text_field_tag :nickname, params[:nickname] %>
      <%= f.submit('検索') %>
    </div>
  <% end %>
  </div>
  </div>