config/routes.rb
Rails.application.routes.draw do
  

  root 'top_pages#home'

  devise_scope :user do
    get     '/signup',         to: 'users/registrations#new'
    post    '/signup',         to: 'users/registrations#create'
    get     '/users/edit',     to: 'users/registrations#edit'
    patch   '/users/:id',      to: 'users/registrations#update'
    delete  '/users/:id',      to: 'users/registrations#delete'
    get     'login',           to: 'users/sessions#new'
    post    '/login',          to: 'users/sessions#create'
    delete  '/logout',         to: 'users/sessions#destroy'
    get     '/password/reset/new', to: 'users/passwords#new'
    post    'user/password',       to: 'users/passwords#create'
    get     'users/password/edit', to: 'users/passwords#edit'
    patch   'users/password', to: 'users/passwords#update'
    
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords', 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  } 
  
  resources :users do
    member do
      get :following, :followers
      get :like
    end
  end
  
  resources :users,         only: [:index, :show, :create, :edit, :destroy]
  resources :microposts,    only: [:create, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes,         only: [:create, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class= "footer">

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "INSTACLONE", root_path , id: "logo" %>
    <nav>
      <ul class ="nav navbar-nav navbar-right">
        
         <% if user_signed_in? %>
         <li><%= link_to "ホーム", root_path %></li>
         <li><%= link_to "ユーザー", users_path %></li>
         <li><%= link_to "マイページ", current_user %></li>
         <li><%= link_to 'プロフィール変更',  edit_user_registration_path(current_user) %> </li>
         <li> <%= link_to "ログアウト", logout_path,method: :delete %></li>
          <li class="divider"></li>
          </ul>
          </li>
          <% else %>
           <li><%= link_to "サインイン",signup_path %></li>
           <li><%= link_to "ログイン",login_path %></li>
           <% end %>
      </ul>
     </nav>
  </div>
</header>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= full_title(yield(:title)) %> | INSTACLONE</title>
    
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= render 'layouts/notifications' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params)if Rails.env.development? %>
    </div>
  </body>
</html>